### PR TITLE
Update 2018-07-18-Data-Structures-for-Beginners-Trees-binary-search-t…

### PR DESCRIPTION
**Pull request by imaverage**
…ree-tutorial.md

### CODE REVIEW

**Comment by amejiarosario** [comment]
@imaverage I'm very thankful for all your fixes! Would you like a free copy of my algorithms book as a token of my gratitude? Just send me your email and will send you the book.

**Comment by imaverage** [comment]
@amejiarosario sure! my email is 69c22463-aaff-4cd6-92b2-be288a5315f1@anonaddy.me

if the book is an attachment over 5MB, please send me an email at that address and I will reply with my real email address :)

**Comment by amejiarosario** [comment]
Great! I sent you the link to download it. Let me know if you get it

**Comment by imaverage** [comment]
it's beautiful - might use this over ctci!

**Pull request merged**
